language: bash
env:
- DOCKER_CLI_EXPERIMENTAL=enabled
services:
  - docker
script:
  - docker buildx create --name builder
  - docker buildx use builder
  - docker buildx inspect --bootstrap
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
  - docker buildx build --platform linux/arm/v7 -t nelsonyaccuzzi/docker-rpi-deluge:latest --push .
